volumes:
  postgres_dev_data:

services:
  data_base:
    environment:
      POSTGRES_DB: ${DB_NAME_POSTGRES}
      POSTGRES_USER: ${DB_USER_POSTGRES}
      POSTGRES_PASSWORD: ${DB_PASSWORD_POSTGRES}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  api:
    ports:
      - "3000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:postgresql://data_base:5432/${DB_NAME_POSTGRES}
      SPRING_DATASOURCE_USERNAME: ${DB_USER_POSTGRES}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD_POSTGRES}